### ISSUE TITLE
No Dll file

### ISSUE THREAD

**Issue by philipbower122** [Hyphen-ated/LiveSplit.HistoryAverage#1]
dll file is required to use this in LiveSplit

**Comment by Hyphen-ated** [comment]
Okay, I uploaded the dll as a release. this project never got past "half-done kinda mostly working" and I'm pretty sure there are weird issues with it, but feel free to give it a shot.

**Comment by philipbower122** [comment]
i will try it out
may i ask where this dll is located as i cannot find it?

**Comment by Hyphen-ated** [comment]
https://github.com/Hyphen-ated/LiveSplit.HistoryAverage/releases

**Comment by philipbower122** [comment]
ok got it thanks
